### ISSUE TITLE
Nat instances not created when using pre existing eips

### ISSUE THREAD

**Issue by krystan** [cloudposse/terraform-aws-dynamic-subnets#101]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
Upon enabling the use of nat instances, disabling nat gateways and specifying the correct number of pre-existing eips the. nat instances are not created, this is NOT the case if you do not supply exiting eips, nat instances are created correctly in that instance.

## Expected Behavior
Create a VPC
Attach an internet gateway.
Create eips
Standup module for dynamic subnets and. specify nat instances and eips to be used.

Subnets should be created with nat instances in public subnets using the pre existing eips

## Steps to Reproduce
1. Get test code from [this gist](https://gist.github.com/krystan/d2dbbd2e4938cc5a14587664e7d3923c)
2. create three eips
3. alter tfvars file to have your own eips in.
4. run terraform init and run
5. Observe that nat instances were not. created.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: Linux
 - Terraform 12.x

## Additional Context
Tried both. manual vpc creation and using a module

**Comment by gregory** [comment]
just ran into this - cc @aknysh
