### ISSUE TITLE
0.0.0.0/0 hard coded for nat instance association

### ISSUE THREAD

**Issue by krystan** [cloudposse/terraform-aws-dynamic-subnets#102]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

It's not always the case that default traffic wants to be routed through an eni (nat instance). Would like the option to specify cidr blocks to route through the nat instance.

## Expected Behavior

Able to supply either a cidr range or list of them to the module so the nat solutions can route specific ranges to the nat instance rather than the hardcoded "anywhere" cidr.

## Use Case

Using transient routing to route to another nat then via vpc peering. Nat not being used for internet purposes.

## Describe Ideal Solution

I'd like to be able to specify the ranges that should be sent to nat. rather than just 0.0.0.0/0

## Alternatives Considered

Turn off nat instances and provision my own :(

**Comment by krystan** [comment]
Hmm I should have been more preceise, this is not an invalid request and I have corrected my language.

**Comment by Nuru** [comment]
@krystan Please provide an example route table illustrating your use case and why it is not possible to achieve the routing results you want by directing the traffic you do not want to go through the NAT to an alternate destination.

**Comment by krystan** [comment]
I'm sorry but that is not possible for various reasons and setting that up
third party would be extremely difficult.

In the end I did indeed use my own .

**Comment by Nuru** [comment]
Closing until a clear use case is provided.
