### ISSUE TITLE
The network acl ids are required in the output for adding or removing security rules

### ISSUE THREAD

**Issue by shrivatsan94** [cloudposse/terraform-aws-dynamic-subnets#148]

**Comment by nitrocode** [comment]
@shrivatsan94 we welcome PRs to all of our modules

https://github.com/cloudposse/terraform-aws-dynamic-subnets/blob/4c97cb1796c822a3d1845a241d0b180758dab57e/private.tf#L61

https://github.com/cloudposse/terraform-aws-dynamic-subnets/blob/345e71e4199f170861f95034e1fc8ec8437ec47b/public.tf#L77
