### ISSUE TITLE
Use a single AZ shared NAT for all private subnets?

### ISSUE THREAD

**Issue by danielloader** [cloudposse/terraform-aws-dynamic-subnets#175]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

I'd like to be able to select a shared NAT gateway deployment for non production use.

**Comment by nachovalera** [comment]
This is a feature we'd like to use for non-production environments.

**Comment by Nuru** [comment]
This feature has been available since May 15, 2022 (#159). Set `max_nats = 1`.
