### ISSUE TITLE
Support aws_vpc_peering_connection

### ISSUE THREAD

**Issue by agrrh** [cloudposse/terraform-aws-dynamic-subnets#30]
After creating VPC and Subnets with your modules, I set up peering with another VPC using native Terraform resources.

Now each time I issue `terrafrom apply`, it wipes out peering connection:

```
  ~ module.dynamic_subnets.aws_route_table.public
      route.#:                                    "2" => "1"
      route.1714026231.cidr_block:                "10.1.1.0/24" => ""
      route.1714026231.egress_only_gateway_id:    "" => ""
      route.1714026231.gateway_id:                "" => ""
      route.1714026231.instance_id:               "" => ""
      route.1714026231.ipv6_cidr_block:           "" => ""
      route.1714026231.nat_gateway_id:            "" => ""
      route.1714026231.network_interface_id:      "" => ""
      route.1714026231.vpc_peering_connection_id: "pcx-<redacted>" => ""
      route.4031220643.cidr_block:                "0.0.0.0/0" => "0.0.0.0/0"
      route.4031220643.egress_only_gateway_id:    "" => ""
      route.4031220643.gateway_id:                "igw-<redacted>" => "igw-<redacted>"
      route.4031220643.instance_id:               "" => ""
      route.4031220643.ipv6_cidr_block:           "" => ""
      route.4031220643.nat_gateway_id:            "" => ""
      route.4031220643.network_interface_id:      "" => ""
      route.4031220643.vpc_peering_connection_id: "" => ""
```

It is possible to run `apply` twice to restore things, but this is probably not the way we want it to work. ;)

It seems for me that this could only be fixed with "lifecycle" property applied to some of inner resources of your module. Probably, ignoring changes on "vpc_peering_connection_id" would do the trick.

**Comment by osterman** [comment]
Hrm.... yea, that looks like a bug.

Also, just pointing out we have a related module for VPC peering, but it won't address this specific issue. 

https://github.com/cloudposse/terraform-aws-vpc-peering

**Comment by Nuru** [comment]
Seems this was fixed a long time ago. If the problem persists in the current version, please open a new issue.
