### ISSUE TITLE
Would be nice if we can provide our own elasticIP while creating nat gateway.

### ISSUE THREAD

**Issue by rverma-nikiai** [cloudposse/terraform-aws-dynamic-subnets#42]
Would be nice if we can provide our own elasticIP while creating a nat gateway. Since elastic IPs are very valuable for some organizations, losing them is difficult (whitelisting issues).
We completely stopped managing elasticIP through any automation tools since it leads to accidental releases. Would be nice if the same can be achieved here.

**Comment by osterman** [comment]
We would accept PR :-)
