### ISSUE TITLE
Fix CIDR recalulcation on new AZ added.

### ISSUE THREAD

**Issue by goruha** [cloudposse/terraform-aws-dynamic-subnets#48]
## Idea
the vars `available_zones`, `enabled_zones`
if `available_zones` is empty - use list of available zones provided by AWS api for the region
if `available_zones` is empty - use list of all `available zones`
CIDR splits on count of `available_zones` but subnets created only for `enabled_zones`
would you like an example?

@osterman yea, that sounds great to me

@Nuru  Well, that was my option B above. I don't like it because existing CIDRs will change when a new AZ becomes available.

@goruha nope
if that happens
we set old AZs list as `available_zones`
and new zone would be ignored

@Nuru 
Well we can always add an intervention to keep the status quo. What I'm talking about is the day the new AZ becomes available and someone runs terraform expecting no changes.

@goruha 
really the solution moves the problem to developer
he can use it for both patterns
he can define list explicit  from the begining (edited) 

@Nuru 
If we split CIDR on `enabled_zones`, which won't change, then no surprise changes happen when a new AZ is added.

@goruha 
but you can not easy add +1 AZ
that's the case

@Nuru 
I don't think adding 1 AZ is going to be easy, even if the old 3 CIDRs do not change.

@goruha 

### initial state

`available_zones = ["us-west-2a", "us-west-2b", "us-west-2c"]`
`enabled_zones = ["us-west-2a", "us-west-2b"]`
we split CIDR into 3 ranges
but use only 2

### future

`available_zones = ["us-west-2a", "us-west-2b", "us-west-2c"]`
`enabled_zones = ["us-west-2a", "us-west-2b", "us-west-2c"]`
enable unused range

### future - AWS added +1 AZ

`available_zones = ["us-west-2a", "us-west-2b", "us-west-2c"]`
`enabled_zones = ["us-west-2a", "us-west-2b", "us-west-2c"]`
nothing changed

### initial state AWS have 3 AZ in the region

`available_zones = []`
`enabled_zones = []`
CIDR splited into 3 ranges, all 3 ranges used

### future - AWS added +1 AZ

terrform plan show the diff that rebuilds subnets because not it want 4 ranges of CIDR
we do
`available_zones = ["us-west-2a", "us-west-2b", "us-west-2c"]` (edited) 
no changes

@Nuru 
Other example: if we split CIDR on `enabled_zones`, which won't change, then no surprise changes happen when a new AZ is added.

## initial state

`available_zones = []`
`enabled_zones = ["us-west-2a", "us-west-2b", "us-west-2c"]`

we split CIDR into 3 ranges
and use 3

### future - AWS added +1 AZ

`available_zones = []`
`enabled_zones = ["us-west-2a", "us-west-2b", "us-west-2c"]`
nothing changed

#### future - AWS added +1 AZ and we want to use 4th zone

`available_zones = []`
`enabled_zones = ["us-west-2a", "us-west-2b", "us-west-2c", "us-west-2d]`
terrform plan show the diff that rebuilds subnets because it want 4 ranges of CIDR (edited) 
I want to be able to run terraform every day and have nothing change

@goruha 

the same
hm..
no

### future - AWS added +1 AZ

`available_zones = []`
`enabled_zones = ["us-west-2a", "us-west-2b", "us-west-2c"]`
nothing changed

terrform plan show the diff that rebuilds subnets because not it want 4 ranges of CIDR
we do
`available_zones = ["us-west-2a", "us-west-2b", "us-west-2c"]` (edited)
you are right that we can not add `us-west-2d` later safty

**Comment by Nuru** [comment]
This issue has been addressed in a few ways, particularly `max_subnet_count`, but fundamentally, if you configure the module to use all the available zones, when AWS adds a new zone, your requirements have changed and that will have a ripple effect. You should explicitly set `max_subnet_count` if you want protection from such changes.
