### ISSUE TITLE
Upgrade sytnax to version .12

### ISSUE THREAD

**Issue by tnielsen2** [cloudposse/terraform-aws-dynamic-subnets#58]
```
Module vpc-subnets (from
"git::https://github.com/cloudposse/terraform-aws-dynamic-subnets.git?ref=master")
does not support Terraform version 0.12.2. To proceed, either choose another
supported Terraform version or update the module's version constraint. Version
constraints are normally set for good reason, so updating the constraint may
lead to other errors or unexpected behavior.
```

Do you guys have any intent on upgrading this to support 0.12.2?

**Comment by lodotek** [comment]
Thanks for posting this, I was having troubles using this module with the latest TF as well...

**Comment by osterman** [comment]
We do, but we are waiting on @Jamie-BitFlight to rebase his PR so we can merge that first

**Comment by osterman** [comment]
https://github.com/cloudposse/terraform-aws-dynamic-subnets/pull/54

**Comment by osterman** [comment]
Thanks @Jamie-BitFlight :-)

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/terraform-aws-dynamic-subnets/releases/tag/0.13.0
