### ISSUE TITLE
More flexible nat instance provision

### ISSUE THREAD

**Issue by puzzloholic** [cloudposse/terraform-aws-dynamic-subnets#73]
Hi,

There is I want to custom about nat instance other than just instance_type. Could you expose more variables upon customizing the instance?
Changes I would like to apply:
- use aws key_pair to enable ssh
- disable public ip, so I can attach own EIP into the instance
- attach nat_monitor.sh into the instance automatically according to this article https://aws.amazon.com/articles/high-availability-for-amazon-vpc-nat-instances-an-example/
- or this https://aws.amazon.com/articles/high-availability-for-amazon-vpc-nat-instances-using-aws-cloudformation-templates/

Thank you.

**Comment by khonourhmrc** [comment]
particularly would like the ability to associate a key pair to the nat instances

**Comment by Nuru** [comment]
With v2 of this module, you can suppress the NAT Instance creation, create your own NAT instances however you like, and add routes to them, so there is a workaround available. However, NAT Instances [are deprecated](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_NAT_Instance.html) and do not support NAT64. I am therefore not inclined to add additional support for them.

**Comment by Nuru** [comment]
You can use a module like https://github.com/int128/terraform-aws-nat-instance (we have not vetted it, just noticed it) to create your own NAT instance outside of the `dynamic-subnets` module and then all you need to do is attach default routes to it:

```hcl
resource "aws_route" "private" {
  count = length(module.dynamic_subnets.private_route_table_ids)

  route_table_id         = module.dynamic_subnets.private_route_table_ids[count.index]
  destination_cidr_block = "0.0.0.0/0"
  network_interface_id   = element(local.nat_instances.*.primary_network_interface_id, count.index)
}
```
