### ISSUE TITLE
Release number is wrong: 0.12.3, shouldn't be 0.18.3?

### ISSUE THREAD

**Issue by nebiros** [cloudposse/terraform-aws-dynamic-subnets#82]
Last release tag number, `0.12.3`: https://github.com/cloudposse/terraform-aws-dynamic-subnets/releases/tag/0.12.3.
Release number before the last release, `0.18.1`: https://github.com/cloudposse/terraform-aws-dynamic-subnets/releases/tag/0.18.1

**Comment by 3h4x** [comment]
I don't think so. This module has branched and 0.12.x is still supporting `tf11` while everything forward is using `tf12`.
This is probably for some backward compatible changes.
